# Generated by Django 4.0.6 on 2022-12-28 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr_login',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.BigIntegerField(default=0)),
                ('village', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mandal', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('seller_id', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
