# Generated by Django 4.1.5 on 2023-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='key',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='qr',
            name='qr',
            field=models.ImageField(default='dumm', upload_to='qr/'),
        ),
        migrations.DeleteModel(
            name='Qr_login',
        ),
    ]
