# Generated by Django 4.1.5 on 2023-01-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_qr_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qr_login',
        ),
    ]
