# Generated by Django 4.1.5 on 2023-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_qr_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='qr',
            name='qr',
            field=models.ImageField(upload_to='qr/'),
        ),
    ]
