# Generated by Django 4.1.5 on 2023-01-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_remove_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='ordered', max_length=10),
        ),
    ]
