# Generated by Django 4.2 on 2023-04-20 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_orders_date_products_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 9, 34, 11, 259760)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 9, 34, 11, 259760)),
        ),
    ]
